"""add foreign key to Review

Revision ID: 753faebb649f
Revises: 55307b0540f1
Create Date: 2024-10-08 06:56:52.762518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753faebb649f'
down_revision = '55307b0540f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_Employee_id_employees'), 'employees', ['Employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_Employee_id_employees'), type_='foreignkey')
        batch_op.drop_column('Employee_id')

    # ### end Alembic commands ###
